
resources:
  - users-deployment.yaml
  - users-service.yaml

commonLabels:
  pavedroad.service: users

commonAnnotations:
  pavedroad.roadctl.version: alphav1
  pavedroad.roadctl.web: www.pavedroad.io
  pavedroad.roadctl.support: support@pavedroad.io

configMapGenerator:
- name: users-configmap
  literals:
  - database-ip=roach-ui
  - ip=0.0.0.0
  - port=8081
