
apiVersion: v1
kind: Service
metadata:
  name: users
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    pavedroad.service: users
  type: NodePort
status:
  loadBalancer: {}
